name: dbt CI

on:
  pull_request:
  push:
    branches: [ main ]

concurrency:
  group: dbt-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  DBT_PROFILES_DIR: ${{ github.workspace }}  # utilise profiles.yml du repo
  DBT_HOST:        ${{ secrets.DBT_HOST }}
  DBT_PORT:        ${{ secrets.DBT_PORT }}
  DBT_DB:          ${{ secrets.DBT_DB }}
  DBT_USER:        ${{ secrets.DBT_USER }}
  DBT_PASSWORD:    ${{ secrets.DBT_PASSWORD }}
  DBT_SCHEMA_DEV:  ${{ secrets.DBT_SCHEMA_DEV }}
  DBT_SCHEMA_PROD: ${{ secrets.DBT_SCHEMA_PROD }}

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # IMPORTANT : linter AVANT toute exécution dbt
      - name: SQLFluff lint
        run: sqlfluff lint . --dialect postgres --exclude-rules ST06,LT05

  build_dev:
    needs: lint
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: dbt deps
        run: dbt deps

      - name: dbt debug (DEV)
        run: dbt debug --target dev

      - name: dbt build (DEV)
        run: dbt build --target dev

  deploy_prod:
    needs: lint
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: dbt deps
        run: dbt deps

      - name: dbt debug (PROD)
        run: dbt debug --target prod

      - name: dbt run (PROD)
        run: dbt run --target prod
